export const fieldAliases: {[key: string] : string} = {
    "OBJECTID": "OBJECTID",
    "NAMOBJ": "Nama Objek",
    "FCODE": "Feature Code",
    "REMARK": "Catatan",
    "METADATA": "METADATA",
    "SRS_ID": "Spatial Reference Spatial Identifier",
    "KDBBPS": "Kode BPS Kabupaten/Kota",
    "KDCBPS": "Kode BPS Kecamatan/Distrik",
    "KDCPUM": "Kode PUM Kecamatan/Distrik",
    "KDEBPS": "Kode BPS Kelurahan/Desa",
    "KDEPUM": "Kode PUM Kelurahan/Desa",
    "KDPBPS": "Kode BPS Provinsi",
    "KDPKAB": "Kode PUM Kabupaten/Kota",
    "KDPPUM": "Kode PUM Provinsi",
    "LUASWH": "Luas Wilayah Menurut Peraturan (HA)",
    "TIPADM": "Tipe Administrasi",
    "WADMKC": "Nama wilayah administrasi Kecamatan atau Distrik",
    "WADMKD": "Nama wilayah administrasi Kelurahan atau Desa",
    "WADMKK": "Nama wilayah administrasi Kebupaten/ Kota",
    "WADMPR": "Nama wilayah administrasi Propinsi",
    "WIADKC": "Nama wilayah induk administrasi Kecamatan/Distrik",
    "WIADKK": "Nama wilayah induk administrasi Kebupaten/ Kota",
    "WIADPR": "Nama wilayah induk administrasi Propinsi",
    "WIADKD": "Nama wilayah induk administrasi Kelurahan/Desa \n",
    "SHAPE_Length": "SHAPE_Length",
    "SHAPE_Area": "SHAPE_Area"
}